---
title: "Results - trade_network"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 400, dev = c("png", "pdf"), error = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(gravity)
library(sf)
library(granatlib)

theme_set(theme_bw())
```

## Highest traded commodities

```{r}
load("raw/all_data1.RData")

raw_data %>% 
  bind_rows() %>% 
  transmute(data = map(data, 2)) %>% 
  unnest() %>% 
  filter(rgDesc == "Export") %>% 
  group_by(cmdDescE) %>% 
  summarise(value = sum(as.numeric(TradeValue)) / 1e9) %>% # billions and billions US dollar
  arrange(desc(value)) %>% 
  head(20) %>% 
  set_names("Commodity", "Total export") %>% 
  mutate_at(1, str_wrap, width = 30) %>% 
  kable_output(caption = "Highest traded commodities")
```


```{r}
load("data/trade_data.RData")
load("data/aux-data.RData")
load("data/eigen.RData") # TODO check
```

```{r}
gravity_df <- trade_avg_df %>% 
  replace_na(list(value = 0)) %>% 
  left_join(trade_aggrement) %>% 
  mutate(across(gcc:nafta, ~ ifelse(is.na(.), FALSE, .))) %>% 
  left_join(rename(gdp_df, geo_from = geo, gdp_from = gdp)) %>% 
  left_join(rename(gdp_df, geo_to = geo, gdp_to = gdp)) %>% 
  left_join(capital_distance_df) %>% 
  left_join(rename(cds_premium_df, geo_from = geo, spread_from = spread)) %>% 
  left_join(rename(cds_premium_df, geo_to = geo, spread_to = spread)) %>% 
  filter(geo_from != "WLD", geo_to != "WLD") %>%
  left_join(eigen_df, by = c("time", "product", "geo_from" = "geo_omit")) %>% 
  filter(geo_from != geo_to) 
```

```{r}
gravity_df <- trade_avg_df %>% 
  mutate(
    g = ifelse(geo_from <= geo_to, str_c(geo_from, geo_to), str_c(geo_to, geo_from)),
    g = str_c(g, time, product)
  ) %>% 
  arrange(desc(value)) %>% 
  filter(!duplicated(g)) %>% 
  select(- g) %>% 
  semi_join(x = gravity_df)
```   

```{r}
c("time", "product", "geo_from", "geo_to", "value", "gcc", "mercosur", "eu", "eurozone", "efta", "comesa", "afta", "nafta", "gdp_from", "gdp_to", "distance_km", "spread_from", "spread_to")
```

## Ei

```{r}
fit_ppml_ei_df <- gravity_df %>% 
  filter(value >= 0) %>%
  mutate(across(starts_with("gdp"), log)) %>% 
  group_by(time, product) %>% 
  nest() %>% 
  mutate(
    fit_ppml =  map(data, ~ {
      gravity::ppml(dependent_variable = "value", distance = "distance_km", additional_regressors = c("gdp_from", "gdp_to", "ei", "spread_from"), data = .)
    })
  )
```

```{r}
fit_ppml_ei_df %>% 
  transmute(
    product, time,
    tidied = map(fit_ppml, broom::tidy)
  ) %>% 
  unnest() %>% 
  filter(product=="total") %>% 
  ggplot() +
  aes(x = as.numeric(time), color = product, y = estimate) +
  facet_wrap(~ term, scales = "free") +
  geom_line()
```

```{r}
fit_ppml_ei_df %>% 
  # filter(product == "total", time == 2019) %>% 
  pull %>% 
  first() %>% 
  plotmo::plotmo()
```

## Panel

```{r}
fit_ppml_ei_df <- gravity_df %>% 
  filter(value >= 0) %>%
  mutate(across(starts_with("gdp"), log)) %>% 
  group_by(product) %>% 
  nest() %>% 
  mutate(
    fit_ppml =  map(data, ~ {
      gravity::ppml(dependent_variable = "value", distance = "distance_km", additional_regressors = c("gdp_from", "gdp_to", "ei", "spread_from"), data = .)
    })
  )
```

## trade aggrement

```{r}
fit_ppml_df <- gravity_df %>% 
  filter(value >= 0) %>%
  mutate(across(starts_with("gdp"), log)) %>% 
  group_by(time, product) %>% 
  nest() %>% 
  mutate(
    fit_ppml =  map(data, ~ {
      gravity::ppml(dependent_variable = "value", distance = "distance_km", additional_regressors = c("gdp_from", "gdp_to", "gcc", "mercosur", "efta", "comesa", "afta", "nafta"), data = .)
    })
  )
```

- mennyire becsüli alá a kapcsolatok értékét

```{r}
fit_ppml_df %>% 
  transmute(
    product, time,
    tidied = map(fit_ppml, broom::tidy)
  ) %>% 
  unnest() %>% 
  filter(product=="total") %>% 
  ggplot() +
  aes(x = as.numeric(time), color = product, y = estimate) +
  facet_wrap(~ term, scales = "free") +
  geom_line()
```

```{r}
fit_ppml_df <- gravity_df %>% 
  filter(value >= 0) %>%
  mutate(across(starts_with("gdp"), log)) %>% 
  mutate_if(is.logical, as.factor) %>% 
  group_by(time, product) %>% 
  nest() %>% 
  mutate(
    fit_ppml =  map(data, ~ {
      gravity::ppml(dependent_variable = "value", distance = "distance_km", additional_regressors = c("gdp_from", "gdp_to", "gcc", "mercosur", "efta", "comesa", "afta", "nafta", "ei", "spread_from"), data = .)
    })
  )
```

```{r}
fit_ppml_df %>% 
  filter(product == "total", time == 2019) %>% 
  pull() %>% 
  first() %>% 
  plotmo::plotmo(inverse.func = log)
```


```{r}
code_label_df <- raw_data_df %>% 
  select(text) %>% 
  distinct() %>% 
  separate(text, c("code", "label"), sep = " - ")

NiceProductName <- function(x, wrap = NULL) {
  out <- map_chr(x, function(current_x) {
    pull(code_label_df, label, code) %>% 
      .[[current_x]]
  })
  
  if (!is.null(wrap)) {
    out <- str_wrap(out, wrap)
  }
  out
}

```


## Gravity model

```{r}
l <- code_label_df %>% 
  mutate(
    code = as.numeric(code),
    code = as.character(code)
         ) %>% 
  pull(label, code)

gravity_fit_df %>% 
  pull(fit_ppml) %>% 
  GGally::ggcoef_compare(variable_labels = l)
```


```{r}
mutate(tidied = map(fit_ppml, broom::tidy)) %>% 
  select(product, tidied) %>% 
  unnest(tidied)
```

```{r}
augmented_ppml_df <- gravity_fit_df %>% 
  mutate(
    augmented = map(fit_ppml, broom::augment),
    data = map(data, drop_na),
    data = map(data, select, geo_from, geo_to)
  ) %>% 
  select(product, data, augmented) %>% 
  unnest(c(data, augmented))
```


```{r}
augmented_ppml_df %>% 
  slice_max(.std.resid, n = 5) %>% 
  summarise(top5std.error = str_c(str_c(geo_from, "-", geo_to), collapse = ", ")) %>% 
  mutate(product = NiceProductName(product)) %>% 
  granatlib::kable_output()
```

```{r}
augmented_ppml_df %>% 
  slice_min(.std.resid, n = 5) %>% 
  summarise(bottom5std.error = str_c(str_c(geo_from, "-", geo_to), collapse = ", ")) %>% 
  mutate(product = NiceProductName(product)) %>% 
  granatlib::kable_output()
```

## Panel

```{r}
gravity_df %>% 
  filter(value >= 0) %>%
  mutate(across(starts_with("gdp"), log)) %>% 
  mutate_if(is.logical, as.factor) %>% 
  group_by(product) %>% 
  nest() %>% 
  mutate(
    fit_ppml =  map(data, ~ {
      gravity::ppml(dependent_variable = "value", distance = "distance_km", additional_regressors = c("gdp_from", "gdp_to", "gcc", "mercosur", "efta", "comesa", "afta", "nafta", "ei", "spread_from"), data = .)
    })
  )
```

